name: Build and Deploy to Main

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy para main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git checkout main || git checkout -b main

          git rm -rf .
          cp -r out/* .
          git add .
          git commit -m "Deploy automático (Next.js build da prod)"
          git push origin main --force
