name: Build and Add Next.js Build to Prod

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout prod
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Commit e push build completo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add -f .next public package.json package-lock.json

          git diff --cached --quiet || git commit -m "Adicionar/Atualizar build Next.js SSR"

          git push origin prod
