name: Build and Deploy to Main

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout prod
        uses: actions/checkout@v4
        with:
          ref: prod

      - name: Instalar dependências
        run: npm ci

      - name: Build
        run: npm run build

     
      - name: Deploy para main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git checkout main || git checkout -b main

          find . -mindepth 1 -not -name '.git' -exec rm -rf {} + || true

          cp -r $GITHUB_WORKSPACE/* .

          echo "node_modules" > .gitignore

          git add .
          git commit -m "Deploy automático (prod + Next.js build)"
          git push origin main --force
